name: $(Year:yyyy).$(Month).$(DayOfMonth)-terraform-apply-prod.$(Rev:r)

parameters:
  - name: terraform_var_file_name 
    displayName: 'Target Environment'
    type: string
    default: 'resource_group_contributor/prod'
    values: 
      # The security domain 'azure_active_directory' can have only one tfvars file "azure_active_directory.tfvars"
      # hence there is no sub-folder
      - azure_active_directory

      # The security domain 'subscription_owner' can have only prod and non-prod tfvars folders
      - subscription_owner/sandbox005prod

      # The security domain 'resource_group_contributor' can have as many tfvars folders as there are environments
      - resource_group_contributor/prod

trigger: none

extends:
  template: ../shared/base.pipeline.yml
  parameters:
    folder: prod
    pipeline: terraform-apply
    stages: 
    - template: azure-pipelines/terraform/templates/stages/terraform-plan-apply.yml@shared_assets
      parameters:
        environment: prod
        container_name: aztfmod_rover
        terraform_configuration_repository: 'caf-terraform-starter'
        terraform_state_container_name: 'cafterraformstarter'
        terraform_var_file_name: ${{ parameters.terraform_var_file_name }}
        service_connection_name_subscription_owner: 'spn-tf-sandboxautomationdemo005-owner-ado-arm-001' # For testing purposes sandbox005 is our PROD subscription 
        service_connection_name_resource_group_contributor: 'spn-tf-cafterraformstarter-prod-contributor-ado-arm-001'  
    